### ISSUE TITLE
Change favicon & title & description metadata

### ISSUE THREAD

**Issue by jordanmaulana** [jordanmaulana/codifyproject#22]
![Image](https://github.com/jordanmaulana/codifyproject/assets/17192308/cff0e82a-395e-481a-b326-8a8194670a0d)

Change Vercel's triangle icon into Codify icon.
Change title metadata from "Create Next App" into "Codivent"
Change description metadata from "Generated by create next app" into "Look no further! Our tickets are the simplest way for you to experience a live event."

**Comment by jordanmaulana** [comment]
hint:
check `src > app > layout.js`

**Comment by jordanmaulana** [comment]
![Image](https://github.com/jordanmaulana/codifyproject/assets/17192308/806a5df3-bd8c-42b5-bacb-594da4c0b276)

ini icon buat favicon nya

**Comment by khardikk** [comment]
Is this issue open?

**Comment by khardikk** [comment]
> here is assignee

was about to create a PR :(

**Comment by jordanmaulana** [comment]
@khardikk Thanks man, but please give a chance for new learners :)
