### ISSUE TITLE
Link event item card to event detail page

### ISSUE THREAD

**Issue by jordanmaulana** [jordanmaulana/codifyproject#29]

**Comment by rifqiizz** [comment]
![Image](https://github.com/jordanmaulana/codifyproject/assets/149316666/ff4efb6a-8ba5-48e8-8b97-433cc177821c)
![Image](https://github.com/jordanmaulana/codifyproject/assets/149316666/8b04fe1a-bde9-4ade-851b-6cd61ce33b30)

Event list linked to Event detail DONE
